### PR TITLE
introduce DESTDIR in Makefile.in for packagers

### PR DESCRIPTION
**Pull request by stefanhusmann**
This patch should make it possible for packagers to work with artanis.

### CODE REVIEW

**Comment by NalaGinrut** [comment]
It seems failed to build, I'm trying to rebuild it. Could you double check it?

**Comment by NalaGinrut** [comment]
@stefanhusmann

The check failed because of the final test step will try to run a simple code to make sure Artanis installed and works fine. And I think the DESTDIR is not in the default load-path of Guile. So it failed to load module of Artanis.

How do you solve such a problem in packaging Guile for Arch? Is there an extra step to add DESTDIR to the load-path of Guile?

**Comment by stefanhusmann** [comment]
Am 13.11.2015 um 08:52 schrieb Mu Lei:
> @stefanhusmann
> 
> The check failed because of the final test step will try to run a simple code to make sure Artanis installed and works fine. And I think the DESTDIR is not in the default load-path of Guile. So it failed to load module of Artanis.
> 
> How do you solve such a problem in packaging Guile for Arch? Is there an extra step to add DESTDIR to the load-path of Guile?
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/NalaGinrut/artanis/pull/54#issuecomment-156356483
> 
Hello,

there is no check function in the PKGBUILD for the guile that comes with Arch Linux.
The code lives here: 
https://projects.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/guile

Or do you mean to add such a check to the creation script for the artanis package?
https://aur.archlinux.org/packages/artanis/

But it should be possible to add such a function. If there is a way to manipulate the load-path temporarily within a script, that should be no problem.

Best Regards 

Stefan

**Comment by NalaGinrut** [comment]
@stefanhusmann 
Thanks for reply, Could you try this test in your console:
```
guile -c '(display (@ (artanis artanis) artanis-version))'
```
The problem is that if this simple test can't pass, then it means it failed to load Artanis module because of wrong load-path setting.

And yes, it's recommended to add such test.
If users specified their own DESTDIR, then it's users' duty to tweak the load-path.  So the test in your case should be:
```
export GUILE_LOAD_PATH=your_dest_dir
guile -c '(display (@ (artanis artanis) artanis-version))'
```

**Comment by stefanhusmann** [comment]
Hello,

Am 13.11.2015 um 12:38 schrieb Mu Lei:

> guile -c '(display (@ (artanis artanis) artanis-version))'

I get
[haawda@frege meine_Pakete]$ guile -c '(display (@ (artanis artanis) artanis-version))'
;;; note: source file /usr/share/guile/2.0/sxml/ssax/input-parse.scm
;;;       newer than compiled /usr/lib/guile/2.0/ccache/sxml/ssax/input-parse.go
;;; found fresh local cache at /home/haawda/.cache/guile/ccache/2.0-LE-8-2.0/usr/share/guile/2.0/sxml/ssax/input-parse.scm.go
GNU Artanis-UNKNOWN[haawda@frege meine_Pakete]$ 

I guess UNKNOWN should be 0.1.0. Oherwise, is this the expected output?

Best Regards 

Stefan

**Comment by NalaGinrut** [comment]
UNKOWN maybe caused by something wrong, but it's trivial.

The Makefile generated for me is:
```
TOP := $(shell pwd)
PREFIX := /usr/local
DESTDIR := @DESTDIR@
SRC := .
```

IIUC, @DESTDIR@ should be expanded to a path. Is this accepted result?

**Comment by stefanhusmann** [comment]
Am 13.11.2015 um 12:56 schrieb Mu Lei:
> UNKOWN maybe caused by something wrong, but it's trivial.
> 
And it seems to be fixed in git, there I get a reasonable version number.
> The Makefile generated for me is:
> ```
> TOP := $(shell pwd)
> PREFIX := /usr/local
> DESTDIR := @DESTDIR@
> SRC := .
> ```
> 
> IIUC, @DESTDIR@ should be expanded to a path. Is this accepted result?
> 
> 
Yes, /usr/local is a sane default, and DESTDIR is empty if not explitely given. That is fine.
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/NalaGinrut/artanis/pull/54#issuecomment-156411323
> 
BTW, the file artanis.texi is not converted into an info file. Should I open a new issue for this?

Best Regards
Stefan

**Comment by NalaGinrut** [comment]
For texinfo issue, it'generated in "make docs".

**Comment by stefanhusmann** [comment]
Am 13.11.2015 um 14:13 schrieb Mu Lei:
> For texinfo issue, it'generated in "make docs".
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/NalaGinrut/artanis/pull/54#issuecomment-156428558
> 
Hello,

I see, but then there we have a similar DESTDIR-issue. I pushed a solution to my github fork.

Best Regards

Stefan

**Comment by NalaGinrut** [comment]
@stefanhusmann 
Could we fix DESTDIR := @DESTDIR@ issue?
If we don't specify DESTDIR while "make", it'll be this when "make install":
```
@DESTDIR@/usr/loca/...
```
This seems won't install Artanis to correct place. Then the simple test will fail, because it find no where to load the Artanis modules.

**Comment by stefanhusmann** [comment]
Am 15.11.2015 um 15:29 schrieb Mu Lei:
> @stefanhusmann 
> Could we fix DESTDIR := @DESTDIR@ issue?
> If we don't specify DESTDIR while "make", it'll be this when "make install":
> ```
> @DESTDIR@/usr/loca/...
> ```
> This seems won't install Artanis to correct place. Then the simple test will fail, because it find no where to load the Artanis modules.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/NalaGinrut/artanis/pull/54#issuecomment-156814964
> 
Hello,

okay, simply remove the line with DESTDIR := @DESTDIR@.

Best Regards

Stefan

**Comment by NalaGinrut** [comment]
@stefanhusmann Thank you very much! All the tests passed, merged and closed. ;-)

**Pull request merged**
